services:
  web:
    image: nginx:latest
    ports:
      - "1234:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www

  php:
    build: .
    volumes:
      - ./src:/var/www
