openapi: 3.0.0
info:
  title: SMAPI
  version: 1.0.0
paths:
  /folders:
    get:
      summary: 'Get media folders list'
      responses:
        '200':
          description: 'Success'
  /images/{folderName}:
    get:
      summary: 'Get images from folderName folder'
      parameters:
        - in: path
          name: folderName
          required: true
          schema:
            type: string
            minimum: 1
      responses:
        '200':
          description: 'Success'
  /swagger:
    get:
      summary: 'DEV ONLY - Get thie swagger file content' 
      responses:
        '200':
          description: 'Success'